apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rutika-ranjolkar/argo-cd-demo.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
*test-1 code*
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
*test-1 code*
    automation:
      selfHeal: true
      prune: true
